# GitHub Sponsors
github: vdhoangson
# Other funding platforms (uncomment and customize as needed)
# ko_fi: vdhoangson
# patreon: vdhoangson
# open_collective: vdhoangson
# tidelift: npm/electron-vue-hosts-editor
# community_bridge: electron-vue-hosts-editor
# liberapay: vdhoangson
# issuehunt: vdhoangson
# otechie: vdhoangson
custom: ["https://paypal.me/vdhson", "https://buymeacoffee.com/vdhoangson"]
